// Code generated by scripts/version.mjs from version.json. DO NOT EDIT.
//
// 修改版本请执行（在仓库根目录）：
// node scripts/version.mjs bump patch     # MALLV0.0.0 -> MALLV0.0.1
// 然后提交 version.json 与本文件。
//
// 三个值均为 var 而非 const：允许构建流水线以 -ldflags 在编译期覆盖，
// 例如 -X email-aggregator-go/src/version.Canonical=... ，
// 用于热修复等需要脱离 version.json 的场景。
// 注意本注释刻意不使用缩进块，以保证 gofmt -l 无输出。
package version

// Canonical 是规范版本号 MALLV<major>.<minor>.<patch>：
// 用户可见版本、安装包文件名、容器镜像 tag、git tag、文档标注一律使用它。
var Canonical = "MALLV0.0.0"

// Semver 是剥离前缀的 x.y.z 形态，供有格式约束的场合使用。
var Semver = "0.0.0"

// Code 是单调递增整数码 = major*10000 + minor*100 + patch。
var Code = 0

// Prefix 是版本前缀，默认 MALLV。
var Prefix = "MALLV"
