// Code generated by scripts/version.mjs from version.json. DO NOT EDIT.
//
// 修改版本请执行（在仓库根目录）：
//     node scripts/version.mjs bump patch     # MALLV0.0.0 -> MALLV0.0.1
//
// 本文件被提交入库（而非 gitignore），保证全新克隆后 `npm run build` 无需
// 先跑版本工具即可通过 —— 避免"构建依赖生成步骤"这类隐式前置条件。

export interface AppVersion {
  /** 规范版本号 MALLV<major>.<minor>.<patch>：用户可见、安装包名、镜像 tag 均用它。 */
  readonly canonical: string
  /** 剥离前缀的 x.y.z 形态，供有格式约束的场合使用。 */
  readonly semver: string
  /** 单调递增整数码 = major*10000 + minor*100 + patch。 */
  readonly code: number
}

export const APP_VERSION: AppVersion = {
  canonical: "MALLV0.0.0",
  semver: "0.0.0",
  code: 0,
} as const

export default APP_VERSION
